//go:build amd64 && !noasm
// DO NOT EDIT - generated by genasm.go

#include "textflag.h"

TEXT ·addConst8(SB), NOSPLIT|NOFRAME, $0-24

    MOVSD   c(FP), X0
    MOVQ    dst+8(FP), AX
    MOVQ    n+16(FP), BX

    MOVQ    $0, R8              // i = 0

    MOVQ    BX, R9              // n-8
    SUBQ    $8, R9

    VBROADCASTSD X0, Y2

Loop:

    VADDPD   (AX)(R8*8), Y2, Y0
    VADDPD   32(AX)(R8*8), Y2, Y1

    VMOVUPD  Y0, (AX)(R8*8)
    VMOVUPD  Y1, 32(AX)(R8*8)

    ADDQ    $8, R8               // i += 8
    CMPQ    R8, R9               // if i > n-8 goto Done
    JGT     Done
    JMP     Loop

Done:
    VZEROUPPER
    RET
